EAS 424 -  Make up "Sign up"
Web-Rangers/Asclepius-website pull request #2
Opened 2022-08-04 10:09 UTC by IrinaEndeladze

2022-08-04 11:47 UTC, NikitoriusMinsk requested changes
The pages should be full width.
Move css files to styles folder

2022-08-04 11:47 UTC, NikitoriusMinsk commented on components/contents/SignUp.js
> +            type="text"
type "email"

2022-08-04 11:47 UTC, NikitoriusMinsk commented on components/contents/SignUp.js
> +            type="number"
dont use type "number" for inputting a phone

2022-08-04 11:47 UTC, NikitoriusMinsk commented on components/contents/SignUp.js
>            <TextField
Separate inputs into components

2022-08-04 12:32 UTC, NikitoriusMinsk requested changes
please fix previous comments

2022-08-04 12:54 UTC, NikitoriusMinsk commented on components/contents/SignUp.js
>            <TextField
i mean move the textfield with its props into a separate component to make it easier to read and reuse

2022-08-04 22:39 UTC, NikitoriusMinsk requested changes

2022-08-04 22:39 UTC, NikitoriusMinsk commented on pages/confirmPasswordPage/index.js
> +      <PasswordConfirm />
A page is a component by itself and shouldn't just return a single component

2022-08-04 22:39 UTC, NikitoriusMinsk commented on pages/confirmPasswordPage/index.js
> +    <div>
use fragments (<> </>) to wrap instead of <_div>

2022-08-04 22:39 UTC, NikitoriusMinsk commented on pages/createNewPass/index.js
> +      <CreateNewPass />
A page is a component by itself and shouldn't just return a single component

2022-08-05 09:33 UTC, IrinaEndeladze commented on pages/confirmPasswordPage/index.js
> +      <PasswordConfirm />
I did it because of Links.  I don't understand how to modify this?

2022-08-05 10:37 UTC, NikitoriusMinsk commented on pages/confirmPasswordPage/index.js
> +      <PasswordConfirm />
The <PasswordConfirm/> shouldn't be a separate component, please just put its code into the page file

2022-08-05 11:36 UTC, merged