Create list of all branches page
Web-Rangers/Asclepius-website pull request #9
Opened 2022-08-15 13:28 UTC by IrinaEndeladze

2022-08-15 13:39 UTC, NikitoriusMinsk commented
I think you renamed the main branch, please don't pull requests this big

2022-08-15 14:33 UTC, NikitoriusMinsk requested changes

2022-08-15 14:33 UTC, NikitoriusMinsk commented on components/ui/Pagination.js
> +  const onNext = () => {
add a check, so the pagination counter doesnt go over max amount of pages

2022-08-15 14:33 UTC, NikitoriusMinsk commented on components/ui/Pagination.js
> +  const onPrevious = () => {
add a check, so the pagination counter doesnt go over min amount of pages

2022-08-15 14:33 UTC, NikitoriusMinsk commented on components/ui/Pagination.js
> +          // eslint-disable-next-line react/jsx-key
add keys, so react knows which component to update on state change

2022-08-15 14:33 UTC, NikitoriusMinsk commented on pages/clinicsPage/index.js
> +      <ClinicPageCardList />
move ClinicPageCardList into the page file

2022-08-15 15:12 UTC, IrinaEndeladze commented on pages/clinicsPage/index.js
> +      <ClinicPageCardList />
it is in pages file

2022-08-16 07:14 UTC, NikitoriusMinsk commented on pages/clinicsPage/index.js
> +      <ClinicPageCardList />
i mean the component's code

2022-08-16 07:16 UTC, NikitoriusMinsk requested changes

2022-08-16 07:16 UTC, NikitoriusMinsk commented on pages/clinicsPage/index.js
> -      <ClinicPageCardList />
check pull request comments

2022-08-16 07:41 UTC, NikitoriusMinsk approved these changes

2022-08-16 07:41 UTC, merged